// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CheckWalkableArgs {
    pub x: u32,
    pub y: u32,
}

impl From<CheckWalkableArgs> for super::Reducer {
    fn from(args: CheckWalkableArgs) -> Self {
        Self::CheckWalkable {
            x: args.x,
            y: args.y,
        }
    }
}

impl __sdk::InModule for CheckWalkableArgs {
    type Module = super::RemoteModule;
}

pub struct CheckWalkableCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `check_walkable`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait check_walkable {
    /// Request that the remote module invoke the reducer `check_walkable` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_check_walkable`] callbacks.
    fn check_walkable(&self, x: u32, y: u32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `check_walkable`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CheckWalkableCallbackId`] can be passed to [`Self::remove_on_check_walkable`]
    /// to cancel the callback.
    fn on_check_walkable(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u32, &u32) + Send + 'static,
    ) -> CheckWalkableCallbackId;
    /// Cancel a callback previously registered by [`Self::on_check_walkable`],
    /// causing it not to run in the future.
    fn remove_on_check_walkable(&self, callback: CheckWalkableCallbackId);
}

impl check_walkable for super::RemoteReducers {
    fn check_walkable(&self, x: u32, y: u32) -> __sdk::Result<()> {
        self.imp
            .call_reducer("check_walkable", CheckWalkableArgs { x, y })
    }
    fn on_check_walkable(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u32, &u32) + Send + 'static,
    ) -> CheckWalkableCallbackId {
        CheckWalkableCallbackId(self.imp.on_reducer(
            "check_walkable",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::CheckWalkable { x, y },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, x, y)
            }),
        ))
    }
    fn remove_on_check_walkable(&self, callback: CheckWalkableCallbackId) {
        self.imp.remove_on_reducer("check_walkable", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `check_walkable`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_check_walkable {
    /// Set the call-reducer flags for the reducer `check_walkable` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn check_walkable(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_check_walkable for super::SetReducerFlags {
    fn check_walkable(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("check_walkable", flags);
    }
}
