// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct FindSpawnsArgs {}

impl From<FindSpawnsArgs> for super::Reducer {
    fn from(args: FindSpawnsArgs) -> Self {
        Self::FindSpawns
    }
}

impl __sdk::InModule for FindSpawnsArgs {
    type Module = super::RemoteModule;
}

pub struct FindSpawnsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `find_spawns`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait find_spawns {
    /// Request that the remote module invoke the reducer `find_spawns` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_find_spawns`] callbacks.
    fn find_spawns(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `find_spawns`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`FindSpawnsCallbackId`] can be passed to [`Self::remove_on_find_spawns`]
    /// to cancel the callback.
    fn on_find_spawns(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> FindSpawnsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_find_spawns`],
    /// causing it not to run in the future.
    fn remove_on_find_spawns(&self, callback: FindSpawnsCallbackId);
}

impl find_spawns for super::RemoteReducers {
    fn find_spawns(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("find_spawns", FindSpawnsArgs {})
    }
    fn on_find_spawns(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> FindSpawnsCallbackId {
        FindSpawnsCallbackId(self.imp.on_reducer(
            "find_spawns",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::FindSpawns {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_find_spawns(&self, callback: FindSpawnsCallbackId) {
        self.imp.remove_on_reducer("find_spawns", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `find_spawns`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_find_spawns {
    /// Set the call-reducer flags for the reducer `find_spawns` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn find_spawns(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_find_spawns for super::SetReducerFlags {
    fn find_spawns(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("find_spawns", flags);
    }
}
