// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GetLayerObjectsArgs {
    pub layer_id: u32,
}

impl From<GetLayerObjectsArgs> for super::Reducer {
    fn from(args: GetLayerObjectsArgs) -> Self {
        Self::GetLayerObjects {
            layer_id: args.layer_id,
        }
    }
}

impl __sdk::InModule for GetLayerObjectsArgs {
    type Module = super::RemoteModule;
}

pub struct GetLayerObjectsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `get_layer_objects`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait get_layer_objects {
    /// Request that the remote module invoke the reducer `get_layer_objects` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_get_layer_objects`] callbacks.
    fn get_layer_objects(&self, layer_id: u32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `get_layer_objects`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`GetLayerObjectsCallbackId`] can be passed to [`Self::remove_on_get_layer_objects`]
    /// to cancel the callback.
    fn on_get_layer_objects(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u32) + Send + 'static,
    ) -> GetLayerObjectsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_get_layer_objects`],
    /// causing it not to run in the future.
    fn remove_on_get_layer_objects(&self, callback: GetLayerObjectsCallbackId);
}

impl get_layer_objects for super::RemoteReducers {
    fn get_layer_objects(&self, layer_id: u32) -> __sdk::Result<()> {
        self.imp
            .call_reducer("get_layer_objects", GetLayerObjectsArgs { layer_id })
    }
    fn on_get_layer_objects(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u32) + Send + 'static,
    ) -> GetLayerObjectsCallbackId {
        GetLayerObjectsCallbackId(self.imp.on_reducer(
            "get_layer_objects",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::GetLayerObjects { layer_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, layer_id)
            }),
        ))
    }
    fn remove_on_get_layer_objects(&self, callback: GetLayerObjectsCallbackId) {
        self.imp.remove_on_reducer("get_layer_objects", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `get_layer_objects`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_get_layer_objects {
    /// Set the call-reducer flags for the reducer `get_layer_objects` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn get_layer_objects(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_get_layer_objects for super::SetReducerFlags {
    fn get_layer_objects(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("get_layer_objects", flags);
    }
}
