// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ListLayersArgs {
    pub map_id: u32,
}

impl From<ListLayersArgs> for super::Reducer {
    fn from(args: ListLayersArgs) -> Self {
        Self::ListLayers {
            map_id: args.map_id,
        }
    }
}

impl __sdk::InModule for ListLayersArgs {
    type Module = super::RemoteModule;
}

pub struct ListLayersCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `list_layers`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait list_layers {
    /// Request that the remote module invoke the reducer `list_layers` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_list_layers`] callbacks.
    fn list_layers(&self, map_id: u32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `list_layers`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ListLayersCallbackId`] can be passed to [`Self::remove_on_list_layers`]
    /// to cancel the callback.
    fn on_list_layers(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u32) + Send + 'static,
    ) -> ListLayersCallbackId;
    /// Cancel a callback previously registered by [`Self::on_list_layers`],
    /// causing it not to run in the future.
    fn remove_on_list_layers(&self, callback: ListLayersCallbackId);
}

impl list_layers for super::RemoteReducers {
    fn list_layers(&self, map_id: u32) -> __sdk::Result<()> {
        self.imp
            .call_reducer("list_layers", ListLayersArgs { map_id })
    }
    fn on_list_layers(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u32) + Send + 'static,
    ) -> ListLayersCallbackId {
        ListLayersCallbackId(self.imp.on_reducer(
            "list_layers",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ListLayers { map_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, map_id)
            }),
        ))
    }
    fn remove_on_list_layers(&self, callback: ListLayersCallbackId) {
        self.imp.remove_on_reducer("list_layers", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `list_layers`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_list_layers {
    /// Set the call-reducer flags for the reducer `list_layers` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn list_layers(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_list_layers for super::SetReducerFlags {
    fn list_layers(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("list_layers", flags);
    }
}
