// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LoadAdditionalMapArgs {
    pub name: String,
    pub tmx_data: String,
}

impl From<LoadAdditionalMapArgs> for super::Reducer {
    fn from(args: LoadAdditionalMapArgs) -> Self {
        Self::LoadAdditionalMap {
            name: args.name,
            tmx_data: args.tmx_data,
        }
    }
}

impl __sdk::InModule for LoadAdditionalMapArgs {
    type Module = super::RemoteModule;
}

pub struct LoadAdditionalMapCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `load_additional_map`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait load_additional_map {
    /// Request that the remote module invoke the reducer `load_additional_map` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_load_additional_map`] callbacks.
    fn load_additional_map(&self, name: String, tmx_data: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `load_additional_map`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`LoadAdditionalMapCallbackId`] can be passed to [`Self::remove_on_load_additional_map`]
    /// to cancel the callback.
    fn on_load_additional_map(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> LoadAdditionalMapCallbackId;
    /// Cancel a callback previously registered by [`Self::on_load_additional_map`],
    /// causing it not to run in the future.
    fn remove_on_load_additional_map(&self, callback: LoadAdditionalMapCallbackId);
}

impl load_additional_map for super::RemoteReducers {
    fn load_additional_map(&self, name: String, tmx_data: String) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "load_additional_map",
            LoadAdditionalMapArgs { name, tmx_data },
        )
    }
    fn on_load_additional_map(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> LoadAdditionalMapCallbackId {
        LoadAdditionalMapCallbackId(self.imp.on_reducer(
            "load_additional_map",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::LoadAdditionalMap { name, tmx_data },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, name, tmx_data)
            }),
        ))
    }
    fn remove_on_load_additional_map(&self, callback: LoadAdditionalMapCallbackId) {
        self.imp
            .remove_on_reducer("load_additional_map", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `load_additional_map`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_load_additional_map {
    /// Set the call-reducer flags for the reducer `load_additional_map` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn load_additional_map(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_load_additional_map for super::SetReducerFlags {
    fn load_additional_map(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("load_additional_map", flags);
    }
}
