// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct QueryTileArgs {
    pub layer_id: u32,
    pub x: u32,
    pub y: u32,
}

impl From<QueryTileArgs> for super::Reducer {
    fn from(args: QueryTileArgs) -> Self {
        Self::QueryTile {
            layer_id: args.layer_id,
            x: args.x,
            y: args.y,
        }
    }
}

impl __sdk::InModule for QueryTileArgs {
    type Module = super::RemoteModule;
}

pub struct QueryTileCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `query_tile`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait query_tile {
    /// Request that the remote module invoke the reducer `query_tile` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_query_tile`] callbacks.
    fn query_tile(&self, layer_id: u32, x: u32, y: u32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `query_tile`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`QueryTileCallbackId`] can be passed to [`Self::remove_on_query_tile`]
    /// to cancel the callback.
    fn on_query_tile(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u32, &u32, &u32) + Send + 'static,
    ) -> QueryTileCallbackId;
    /// Cancel a callback previously registered by [`Self::on_query_tile`],
    /// causing it not to run in the future.
    fn remove_on_query_tile(&self, callback: QueryTileCallbackId);
}

impl query_tile for super::RemoteReducers {
    fn query_tile(&self, layer_id: u32, x: u32, y: u32) -> __sdk::Result<()> {
        self.imp
            .call_reducer("query_tile", QueryTileArgs { layer_id, x, y })
    }
    fn on_query_tile(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u32, &u32, &u32) + Send + 'static,
    ) -> QueryTileCallbackId {
        QueryTileCallbackId(self.imp.on_reducer(
            "query_tile",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::QueryTile { layer_id, x, y },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, layer_id, x, y)
            }),
        ))
    }
    fn remove_on_query_tile(&self, callback: QueryTileCallbackId) {
        self.imp.remove_on_reducer("query_tile", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `query_tile`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_query_tile {
    /// Set the call-reducer flags for the reducer `query_tile` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn query_tile(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_query_tile for super::SetReducerFlags {
    fn query_tile(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("query_tile", flags);
    }
}
