// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TiledLayer {
    pub layer_id: u32,
    pub map_id: u32,
    pub name: String,
    pub layer_type: String,
    pub visible: bool,
    pub opacity: f32,
    pub offset_x: i32,
    pub offset_y: i32,
    pub z_order: u32,
}

impl __sdk::InModule for TiledLayer {
    type Module = super::RemoteModule;
}
