// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::tiled_tileset_type::TiledTileset;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `tiled_tileset`.
///
/// Obtain a handle from the [`TiledTilesetTableAccess::tiled_tileset`] method on [`super::RemoteTables`],
/// like `ctx.db.tiled_tileset()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tiled_tileset().on_insert(...)`.
pub struct TiledTilesetTableHandle<'ctx> {
    imp: __sdk::TableHandle<TiledTileset>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `tiled_tileset`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TiledTilesetTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TiledTilesetTableHandle`], which mediates access to the table `tiled_tileset`.
    fn tiled_tileset(&self) -> TiledTilesetTableHandle<'_>;
}

impl TiledTilesetTableAccess for super::RemoteTables {
    fn tiled_tileset(&self) -> TiledTilesetTableHandle<'_> {
        TiledTilesetTableHandle {
            imp: self.imp.get_table::<TiledTileset>("tiled_tileset"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TiledTilesetInsertCallbackId(__sdk::CallbackId);
pub struct TiledTilesetDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TiledTilesetTableHandle<'ctx> {
    type Row = TiledTileset;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TiledTileset> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TiledTilesetInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TiledTilesetInsertCallbackId {
        TiledTilesetInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TiledTilesetInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TiledTilesetDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TiledTilesetDeleteCallbackId {
        TiledTilesetDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TiledTilesetDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TiledTileset>("tiled_tileset");
    _table.add_unique_constraint::<u32>("tileset_id", |row| &row.tileset_id);
}
pub struct TiledTilesetUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TiledTilesetTableHandle<'ctx> {
    type UpdateCallbackId = TiledTilesetUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TiledTilesetUpdateCallbackId {
        TiledTilesetUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TiledTilesetUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TiledTileset>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TiledTileset>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `tileset_id` unique index on the table `tiled_tileset`,
/// which allows point queries on the field of the same name
/// via the [`TiledTilesetTilesetIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tiled_tileset().tileset_id().find(...)`.
pub struct TiledTilesetTilesetIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TiledTileset, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TiledTilesetTableHandle<'ctx> {
    /// Get a handle on the `tileset_id` unique index on the table `tiled_tileset`.
    pub fn tileset_id(&self) -> TiledTilesetTilesetIdUnique<'ctx> {
        TiledTilesetTilesetIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("tileset_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TiledTilesetTilesetIdUnique<'ctx> {
    /// Find the subscribed row whose `tileset_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<TiledTileset> {
        self.imp.find(col_val)
    }
}
