// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::tiled_object_type::TiledObject;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `tiled_object`.
///
/// Obtain a handle from the [`TiledObjectTableAccess::tiled_object`] method on [`super::RemoteTables`],
/// like `ctx.db.tiled_object()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tiled_object().on_insert(...)`.
pub struct TiledObjectTableHandle<'ctx> {
    imp: __sdk::TableHandle<TiledObject>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `tiled_object`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TiledObjectTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TiledObjectTableHandle`], which mediates access to the table `tiled_object`.
    fn tiled_object(&self) -> TiledObjectTableHandle<'_>;
}

impl TiledObjectTableAccess for super::RemoteTables {
    fn tiled_object(&self) -> TiledObjectTableHandle<'_> {
        TiledObjectTableHandle {
            imp: self.imp.get_table::<TiledObject>("tiled_object"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TiledObjectInsertCallbackId(__sdk::CallbackId);
pub struct TiledObjectDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TiledObjectTableHandle<'ctx> {
    type Row = TiledObject;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TiledObject> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TiledObjectInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TiledObjectInsertCallbackId {
        TiledObjectInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TiledObjectInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TiledObjectDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TiledObjectDeleteCallbackId {
        TiledObjectDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TiledObjectDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TiledObject>("tiled_object");
    _table.add_unique_constraint::<u64>("object_id", |row| &row.object_id);
}
pub struct TiledObjectUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TiledObjectTableHandle<'ctx> {
    type UpdateCallbackId = TiledObjectUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TiledObjectUpdateCallbackId {
        TiledObjectUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TiledObjectUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TiledObject>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TiledObject>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `object_id` unique index on the table `tiled_object`,
/// which allows point queries on the field of the same name
/// via the [`TiledObjectObjectIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tiled_object().object_id().find(...)`.
pub struct TiledObjectObjectIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TiledObject, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TiledObjectTableHandle<'ctx> {
    /// Get a handle on the `object_id` unique index on the table `tiled_object`.
    pub fn object_id(&self) -> TiledObjectObjectIdUnique<'ctx> {
        TiledObjectObjectIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("object_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TiledObjectObjectIdUnique<'ctx> {
    /// Find the subscribed row whose `object_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TiledObject> {
        self.imp.find(col_val)
    }
}
