// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::tiled_tile_type::TiledTile;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `tiled_tile`.
///
/// Obtain a handle from the [`TiledTileTableAccess::tiled_tile`] method on [`super::RemoteTables`],
/// like `ctx.db.tiled_tile()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tiled_tile().on_insert(...)`.
pub struct TiledTileTableHandle<'ctx> {
    imp: __sdk::TableHandle<TiledTile>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `tiled_tile`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TiledTileTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TiledTileTableHandle`], which mediates access to the table `tiled_tile`.
    fn tiled_tile(&self) -> TiledTileTableHandle<'_>;
}

impl TiledTileTableAccess for super::RemoteTables {
    fn tiled_tile(&self) -> TiledTileTableHandle<'_> {
        TiledTileTableHandle {
            imp: self.imp.get_table::<TiledTile>("tiled_tile"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TiledTileInsertCallbackId(__sdk::CallbackId);
pub struct TiledTileDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TiledTileTableHandle<'ctx> {
    type Row = TiledTile;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TiledTile> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TiledTileInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TiledTileInsertCallbackId {
        TiledTileInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TiledTileInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TiledTileDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TiledTileDeleteCallbackId {
        TiledTileDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TiledTileDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TiledTile>("tiled_tile");
    _table.add_unique_constraint::<u64>("tile_id", |row| &row.tile_id);
}
pub struct TiledTileUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TiledTileTableHandle<'ctx> {
    type UpdateCallbackId = TiledTileUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TiledTileUpdateCallbackId {
        TiledTileUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TiledTileUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TiledTile>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TiledTile>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `tile_id` unique index on the table `tiled_tile`,
/// which allows point queries on the field of the same name
/// via the [`TiledTileTileIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tiled_tile().tile_id().find(...)`.
pub struct TiledTileTileIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TiledTile, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TiledTileTableHandle<'ctx> {
    /// Get a handle on the `tile_id` unique index on the table `tiled_tile`.
    pub fn tile_id(&self) -> TiledTileTileIdUnique<'ctx> {
        TiledTileTileIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("tile_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TiledTileTileIdUnique<'ctx> {
    /// Find the subscribed row whose `tile_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TiledTile> {
        self.imp.find(col_val)
    }
}
