// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::tiled_map_type::TiledMap;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `tiled_map`.
///
/// Obtain a handle from the [`TiledMapTableAccess::tiled_map`] method on [`super::RemoteTables`],
/// like `ctx.db.tiled_map()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tiled_map().on_insert(...)`.
pub struct TiledMapTableHandle<'ctx> {
    imp: __sdk::TableHandle<TiledMap>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `tiled_map`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TiledMapTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TiledMapTableHandle`], which mediates access to the table `tiled_map`.
    fn tiled_map(&self) -> TiledMapTableHandle<'_>;
}

impl TiledMapTableAccess for super::RemoteTables {
    fn tiled_map(&self) -> TiledMapTableHandle<'_> {
        TiledMapTableHandle {
            imp: self.imp.get_table::<TiledMap>("tiled_map"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TiledMapInsertCallbackId(__sdk::CallbackId);
pub struct TiledMapDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TiledMapTableHandle<'ctx> {
    type Row = TiledMap;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TiledMap> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TiledMapInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TiledMapInsertCallbackId {
        TiledMapInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TiledMapInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TiledMapDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TiledMapDeleteCallbackId {
        TiledMapDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TiledMapDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TiledMap>("tiled_map");
    _table.add_unique_constraint::<u32>("map_id", |row| &row.map_id);
}
pub struct TiledMapUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TiledMapTableHandle<'ctx> {
    type UpdateCallbackId = TiledMapUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TiledMapUpdateCallbackId {
        TiledMapUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TiledMapUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TiledMap>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TiledMap>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `map_id` unique index on the table `tiled_map`,
/// which allows point queries on the field of the same name
/// via the [`TiledMapMapIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tiled_map().map_id().find(...)`.
pub struct TiledMapMapIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TiledMap, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TiledMapTableHandle<'ctx> {
    /// Get a handle on the `map_id` unique index on the table `tiled_map`.
    pub fn map_id(&self) -> TiledMapMapIdUnique<'ctx> {
        TiledMapMapIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("map_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TiledMapMapIdUnique<'ctx> {
    /// Find the subscribed row whose `map_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<TiledMap> {
        self.imp.find(col_val)
    }
}
