// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::tiled_layer_type::TiledLayer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `tiled_layer`.
///
/// Obtain a handle from the [`TiledLayerTableAccess::tiled_layer`] method on [`super::RemoteTables`],
/// like `ctx.db.tiled_layer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tiled_layer().on_insert(...)`.
pub struct TiledLayerTableHandle<'ctx> {
    imp: __sdk::TableHandle<TiledLayer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `tiled_layer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TiledLayerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TiledLayerTableHandle`], which mediates access to the table `tiled_layer`.
    fn tiled_layer(&self) -> TiledLayerTableHandle<'_>;
}

impl TiledLayerTableAccess for super::RemoteTables {
    fn tiled_layer(&self) -> TiledLayerTableHandle<'_> {
        TiledLayerTableHandle {
            imp: self.imp.get_table::<TiledLayer>("tiled_layer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TiledLayerInsertCallbackId(__sdk::CallbackId);
pub struct TiledLayerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TiledLayerTableHandle<'ctx> {
    type Row = TiledLayer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TiledLayer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TiledLayerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TiledLayerInsertCallbackId {
        TiledLayerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TiledLayerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TiledLayerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TiledLayerDeleteCallbackId {
        TiledLayerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TiledLayerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TiledLayer>("tiled_layer");
    _table.add_unique_constraint::<u32>("layer_id", |row| &row.layer_id);
}
pub struct TiledLayerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TiledLayerTableHandle<'ctx> {
    type UpdateCallbackId = TiledLayerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TiledLayerUpdateCallbackId {
        TiledLayerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TiledLayerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TiledLayer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TiledLayer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `layer_id` unique index on the table `tiled_layer`,
/// which allows point queries on the field of the same name
/// via the [`TiledLayerLayerIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tiled_layer().layer_id().find(...)`.
pub struct TiledLayerLayerIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TiledLayer, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TiledLayerTableHandle<'ctx> {
    /// Get a handle on the `layer_id` unique index on the table `tiled_layer`.
    pub fn layer_id(&self) -> TiledLayerLayerIdUnique<'ctx> {
        TiledLayerLayerIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("layer_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TiledLayerLayerIdUnique<'ctx> {
    /// Find the subscribed row whose `layer_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<TiledLayer> {
        self.imp.find(col_val)
    }
}
