// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TiledProperty {
    pub property_id: u64,
    pub parent_type: String,
    pub parent_id: u64,
    pub key: String,
    pub value: String,
    pub value_type: String,
}

impl __sdk::InModule for TiledProperty {
    type Module = super::RemoteModule;
}
