// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TiledTileset {
    pub tileset_id: u32,
    pub map_id: u32,
    pub tileset_index: u32,
    pub name: String,
    pub tile_width: u32,
    pub tile_height: u32,
    pub tile_count: u32,
    pub columns: u32,
    pub image_source: Option<String>,
    pub image_width: Option<u32>,
    pub image_height: Option<u32>,
}

impl __sdk::InModule for TiledTileset {
    type Module = super::RemoteModule;
}
