// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::tiled_property_type::TiledProperty;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `tiled_property`.
///
/// Obtain a handle from the [`TiledPropertyTableAccess::tiled_property`] method on [`super::RemoteTables`],
/// like `ctx.db.tiled_property()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tiled_property().on_insert(...)`.
pub struct TiledPropertyTableHandle<'ctx> {
    imp: __sdk::TableHandle<TiledProperty>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `tiled_property`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TiledPropertyTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TiledPropertyTableHandle`], which mediates access to the table `tiled_property`.
    fn tiled_property(&self) -> TiledPropertyTableHandle<'_>;
}

impl TiledPropertyTableAccess for super::RemoteTables {
    fn tiled_property(&self) -> TiledPropertyTableHandle<'_> {
        TiledPropertyTableHandle {
            imp: self.imp.get_table::<TiledProperty>("tiled_property"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TiledPropertyInsertCallbackId(__sdk::CallbackId);
pub struct TiledPropertyDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TiledPropertyTableHandle<'ctx> {
    type Row = TiledProperty;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TiledProperty> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TiledPropertyInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TiledPropertyInsertCallbackId {
        TiledPropertyInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TiledPropertyInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TiledPropertyDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TiledPropertyDeleteCallbackId {
        TiledPropertyDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TiledPropertyDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TiledProperty>("tiled_property");
    _table.add_unique_constraint::<u64>("property_id", |row| &row.property_id);
}
pub struct TiledPropertyUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TiledPropertyTableHandle<'ctx> {
    type UpdateCallbackId = TiledPropertyUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TiledPropertyUpdateCallbackId {
        TiledPropertyUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TiledPropertyUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TiledProperty>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TiledProperty>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `property_id` unique index on the table `tiled_property`,
/// which allows point queries on the field of the same name
/// via the [`TiledPropertyPropertyIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tiled_property().property_id().find(...)`.
pub struct TiledPropertyPropertyIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TiledProperty, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TiledPropertyTableHandle<'ctx> {
    /// Get a handle on the `property_id` unique index on the table `tiled_property`.
    pub fn property_id(&self) -> TiledPropertyPropertyIdUnique<'ctx> {
        TiledPropertyPropertyIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("property_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TiledPropertyPropertyIdUnique<'ctx> {
    /// Find the subscribed row whose `property_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TiledProperty> {
        self.imp.find(col_val)
    }
}
