[package]
name = "bevy_tiled_client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bevy_client"
path = "src/main.rs"

[dependencies]
bevy = "0.16"
bevy_spacetimedb = "1.0"
log = "0.4"
spacetimedb-sdk = "1.4"
